run:
  build-tags:
    - js
    - wasm

linters:
  disable:
    - gci
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - style
    - test
    - unused

linters-settings:
  goimports:
    local-prefixes: github.com/paulvollmer/helm-playground
  varnamelen:
    ignore-names:
      - err
      - tt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test.go
      linters:
        - funlen