run:
  go: "1.18"
  build-tags:
    - js
    - wasm

linters:
  enable-all: true
  disable:
    - gci
    # deprecated linter
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck

linters-settings:
  goimports:
    local-prefixes: github.com/paulvollmer/helm-playground
  varnamelen:
    ignore-names:
      - err
      - tt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test.go
      linters:
        - funlen