run:
  build-tags:
    - js
    - wasm

linters:
  disable:
    - gci
  presets:
#    - bugs
    - comment
#    - complexity
#    - error
    - format
#    - import
#    - metalinter
#    - module
#    - performance
#    - style
#    - test
#    - unused

linters-settings:
  goimports:
    local-prefixes: github.com/paulvollmer/helm-playground
