name: CD

on:
  push:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-wasm:
    uses: paulvollmer/helm-playground/.github/workflows/build-wasm.yaml@main

  build-app:
    uses: paulvollmer/helm-playground/.github/workflows/build-app.yaml@main

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [build-wasm, build-app]
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: react-build
          path: build
      
      - uses: actions/download-artifact@v2
        with:
          name: wasm-build
          path: build
      
      - uses: actions/download-artifact@v2
        with:
          name: wasm-exec
          path: build

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
