name: CI

on:
  pull_request:

jobs:
  build-wasm:
    uses: paulvollmer/helm-playground/.github/workflows/build-wasm.yaml@main

  build-app:
    uses: paulvollmer/helm-playground/.github/workflows/build-app.yaml@main
